import food from "@assets/wedding_caterers.jpg";

export const veg_menu = [
  {
    name: "Welcome Drinks",
    items: [
      { name: "Soft Drinks", image: food },
      { name: "Fruit Juices", image: food },
    ],
  },
  {
    name: "Pickles/Pachadi",
    items: [
      { name: "Dosakaya", image: food },
      { name: "Tomato", image: food },
      { name: "Mango", image: food },
      { name: "Red Chilli", image: food },
    ],
  },
  {
    name: "Dry Curries",
    items: [
      { name: "Bhendi Fry", image: food },
      { name: "Veg 65", image: food },
      { name: "Aloo Fry", image: food },
      { name: "Carrot Beans Fry", image: food },
      { name: "Vankaya", image: food },
      { name: "Pakoda", image: food },
      { name: "Gobi pakoda", image: food },
      { name: "Kanda Fry", image: food },
    ],
  },
  {
    name: "Dal",
    items: [
      { name: "Tomato Dal", image: food },
      { name: "Palak Dal", image: food },
      { name: "Dal Tadka", image: food },
      { name: "Mango Dal", image: food },
      { name: "Dal Makhani", image: food },
      { name: "Sambar", image: food },
      { name: "Gongura Dal", image: food },
    ],
  },
  {
    name: "Starters",
    items: [
      { name: "Gobi Manchurian", image: food },
      { name: "Aloo 65", image: food },
      { name: "Veg bullets", image: food },
      { name: "Chrisy Veg", image: food },
      { name: "Spring rolls", image: food },
      { name: "Shanghai rolls", image: food },
      { name: "Baby corns", image: food },
      { name: "Majestic", image: food },
      { name: "Chili Mushrooms", image: food },
    ],
  },
  {
    name: "Snacks",
    items: [
      { name: "Green Salad", image: food },
      { name: "Aloo Chat", image: food },
      { name: "Aloo Channa", image: food },
      { name: "Chat", image: food },
      { name: "Peanut Chat", image: food },
      { name: "Cucumber", image: food },
      { name: "Yoghurt", image: food },
    ],
  },
  {
    name: "Gravy Curries",
    items: [
      { name: "Bagara Baingan", image: food },
      { name: "Gutti Vankaya", image: food },
      { name: "Mixed Veg Curry", image: food },
      { name: "Tomato Munakad", image: food },
      { name: "Tomato Mirchi", image: food },
      { name: "Masala", image: food },
      { name: "Capsicum Masala", image: food },
      { name: "Chana Masala", image: food },
      { name: "Veg Kadai", image: food },
      { name: "Baby Corn Masal", image: food },
      { name: "Aloo Tomato Kur", image: food },
      { name: "Gobi Manchurian", image: food },
      { name: "Gravy", image: food },
      { name: "Mirchi ka Salan", image: food },
      { name: "Paneer Masala", image: food },
      { name: "Kaju Paneer", image: food },
      { name: "Aloo Gobi", image: food },
      { name: "Palak Paneer", image: food },
    ],
  },
  {
    name: "Curd/Raitha",
    items: [
      { name: "Plain Curd", image: food },
      { name: "Cucumber Raitha", image: food },
      { name: "Mixed Raitha", image: food },
      { name: "Boondi Raitha", image: food },
      { name: "Tomato Raitha", image: food },
      { name: "Onion Raitha", image: food },
    ],
  },
  {
    name: "Desert",
    items: [
      { name: "Ras Malai", image: food },
      { name: "Khadu Kheer", image: food },
      { name: "Trifle Pudding", image: food },
      { name: "Basundi", image: food },
    ],
  },
  {
    name: "Sweets",
    items: [
      { name: "Kala Jamun", image: food },
      { name: "Qurbani Ka", image: food },
      { name: "Meetha", image: food },
      { name: "Carrot Halwa", image: food },
      { name: "Semiya Payasam", image: food },
      { name: "Double Ka", image: food },
      { name: "Meetha Gulab", image: food },
      { name: "Jamun", image: food },
      { name: "Fruit Salad", image: food },
      { name: "Custard", image: food },
    ],
  },
];
